import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'

const poppins = Poppins({ weight: ['300','400', '500', '700', '800'], subsets: ['latin', 'latin-ext']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={`${poppins.className} bg-primary flex flex-coll items-center justify-center`}>
        
        {children}
      </body>
    </html>
  )
}
